---
- hosts: all
  become: true
  tasks:
     - name: installing git
       apt: name=git state=latest
     - name: creating dir
       file:
           path: /home/ubuntu/enlightdevops
           state: directory
           owner: ubuntu
           
           
           #- name: clone repo
           # git:
           # repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpassword | urlencode }}@gitlab.com/enlightdevops/enlight_gitlab.git"
           #dest: "/home/ubuntu/enlightdevops"
           # force: yes
           # branch: main
     - name: installing nginx
       apt: name=nginx state=latest
     - name: copying nginx config
       copy:
           src: "template/demo.conf"
           dest: "/etc/nginx/sites-available/demo.conf"
           owner: root
           group: root
           mode: 0644
     - name: linking a file in nginx
       file:
           src: "/etc/nginx/sites-available/demo.conf"
           dest: "/etc/nginx/sites-enabled/demo.conf"
           state: link     
           owner: root
           group: root

     - name: restaring nginx
       service: name=nginx state=restarted
     - name: installing Mysql
       apt: name=mysql-server state=latest

     - name: installing mysql extention
       apt: name=python3-mysqldb state=latest

     - name: creating group
       group: name=demo state=present

     - name: craete user
       user: name=demo groups=demo createhome=yes append=yes




