---
- hosts: all
  become: true
  tasks:
     - name: installing git
       apt: name=git state=latest
     - name: creating dir
       file:
           path: /home/ubuntu/enlightdevops
           state: directory
           owner: ubuntu
           
           
           #- name: clone repo
           # git:
           # repo: "https://{{ gitlabuser | urlencode }}:{{ gitlabpassword | urlencode }}@gitlab.com/enlightdevops/enlight_gitlab.git"
           #dest: "/home/ubuntu/enlightdevops"
           # force: yes
           # branch: main




