---

- hosts: all
  become: true
  tasks:
       - name: installing git
         apt: 
          name: git
          state: latest
       - name: installing nginx
         apt: name=nginx state=latest
       - name: updagrading the patches
         command: sudo apt -y upgrade
       - name: restart nginx
         service: name=nginx state=restartted

