---
     - name: installing nginx
       apt: name=nginx state=latest
     - name: copying nginx config
       copy:
           src: "templates/demo.conf"
           dest: "/etc/nginx/sites-available/demo.conf"
           owner: root
           group: root
           mode: 0644
     - name: linking a file in nginx
       file:
           src: "/etc/nginx/sites-available/demo.conf"
           dest: "/etc/nginx/sites-enabled/demo.conf"
           state: link     
           owner: root
           group: root
           mode: 775
       notify:
          - nginx restart
     - debug:
         msg: "hello all this {{inst}} from {{places}} we teach {{course}}"



