- name: launching an ec2 instance
  ec2:
        key_name: ansible_key
        group_id: sg-070aa330c50368732
        instance_type: t2.micro
        image: ami-0c1a7f89451184c8b
        wait: yes
        count: 1
        volumes:
               - device_name: /dev/sda1
                 volume_size: 20
        region: ap-south-1
        instance_tags:
          Name: ansible-slave
